//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace uWebshop.Package.Installer {
    
    
    public partial class uWebshopInstaller
    {

	    protected global::System.Web.UI.WebControls.Label Label1;
		protected global::System.Web.UI.WebControls.TextBox txtStoreAlias;
		protected global::System.Web.UI.WebControls.Button btnInstallStore;
		protected global::System.Web.UI.WebControls.Label lblStorePicker;
		protected global::System.Web.UI.WebControls.PlaceHolder phInstallStorePicker;
		protected global::System.Web.UI.WebControls.Button btnInstallStorePicker;

		protected global::umbraco.uicontrols.Pane panel2;
		protected global::umbraco.uicontrols.Pane panel3;
		protected global::umbraco.uicontrols.Pane panel5;
    }
}
