//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace uWebshop.Package.Installer {
    
    
    public partial class uWebshopDashBoard {
        protected global::System.Web.UI.WebControls.Literal uwbsVersionInfo;

	    protected global::umbraco.uicontrols.Pane pane1;

	    protected global::umbraco.uicontrols.Pane panel3;
		protected global::umbraco.uicontrols.Pane panel5;
	    protected global::umbraco.uicontrols.Pane panel6;

		protected global::System.Web.UI.WebControls.Label lblStorePicker;
		protected global::System.Web.UI.WebControls.PlaceHolder phInstallStorePicker;
		protected global::System.Web.UI.WebControls.Button btnInstallStorePicker;

	    protected global::System.Web.UI.UpdatePanel ordersUpdatePanel;
		protected global::System.Web.UI.UpdateProgress ordersUpdateProgress;
		protected global::System.Web.UI.WebControls.Button upgradeToCurrentVersionButton;
    }
}
